### ISSUE TITLE
Mailscanner doesn't mark virus infected message (inline warning)

### ISSUE THREAD

**Issue by TLINDEN** [MailScanner/v5#225] opened 2018-09-19 10:23 UTC
Our Mailscanner doesn't mark infected mails sometimes with the inline warning, although it's enabled.

Logs say:
```
Sep 19 10:41:09 s4mailscan2 clamd[83862]: /localdisk/MailScanner/tmp/80613/57CD545C5307.A95B8/nKonkretisierun-1.doc: PUA.Pdf.Trojan.EmbeddedJavaScript-1 FOUND
Sep 19 10:41:09 s4mailscan2 clamd[83862]: /localdisk/MailScanner/tmp/80613/57CD545C5307.A95B8/z22oleObject1.bin: PUA.Pdf.Trojan.EmbeddedJavaScript-1 FOUND
Sep 19 10:41:09 s4mailscan2 MailScanner[80613]: Clamd::INFECTED:: PUA.Pdf.Trojan.EmbeddedJavaScript-1 :: ./57CD545C5307.A95B8/Konkretisierun-1.doc
Sep 19 10:41:09 s4mailscan2 MailScanner[80613]: Clamd::INFECTED:: PUA.Pdf.Trojan.EmbeddedJavaScript-1 :: ./57CD545C5307.A95B8/22oleObject1.bin
Sep 19 10:41:09 s4mailscan2 MailScanner[80613]: Infected message 57CD545C5307.A95B8 came from *.*.*.*
Sep 19 10:41:09 s4mailscan2 MailScanner[80613]: Saved entire message to /var/spool/postfix/MailScanner/quarantine/20180919/57CD545C5307.A95B8
Sep 19 10:41:09 s4mailscan2 MailScanner[80613]: Saved infected "Konkretisierun-1.doc" to /var/spool/postfix/MailScanner/quarantine/20180919/57CD545C5307.A95B8
Sep 19 10:41:09 s4mailscan2 MailScanner[80613]: Saved infected "22oleObject1.bin" to /var/spool/postfix/MailScanner/quarantine/20180919/57CD545C5307.A95B8
Sep 19 10:41:09 s4mailscan2 MailScanner[80613]: Message 57CD545C5307.A95B8 from *.*.*.* (foo@bar) to bar is not spam, SpamAssassin (nicht zwischen gespeichert, Wertung=0, benoetigt 6, autolearn=disabled)
Sep 19 10:41:09 s4mailscan2 MailScanner[80613]: Requeue: 57CD545C5307.A95B8 to 0A96A45F7289
```

The message is a correct multipart/mime message with one text/html and one text/plain part:
```
--=_mixed 002FB483C125830D_=
Content-Type: multipart/alternative; boundary="=_alternative 002FB483C125830D_="

--=_alternative 002FB483C125830D_=
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset="ISO-8859-1"

text body

--=_alternative 002FB483C125830D_=
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset="ISO-8859-1"

html body
```
The attachment in question has been quarantined and replaced in the mail to the receipient with the txt warning file. However, the inline message in the body is missing.

This only happens in some cases, most of the time, messages are being marked inline as configured.

**Comment by shawniverson** [comment] 2018-09-19 10:30
How is your inline warning rule enabled?  Are you using a ruleset or not?  
Do you have silent viruses enabled?  Do you have spam viruses enabled?  

Please share relevant parts of your configuration so we can dig deeper.

**Comment by TLINDEN** [comment] 2018-09-19 10:43
```
Mark Infected Messages = yes
Inline HTML Signature = %report-dir%/inline.sig.html
Inline Text Signature = %report-dir%/inline.sig.txt
Inline HTML Warning = %report-dir%/inline.warning.html
Inline Text Warning = %report-dir%/inline.warning.txt
Silent Viruses = 
Still Deliver Silent Viruses = yes
Spam-Virus Header = X-%org-name%-MailScanner-SpamVirus-Report:
Virus Names Which Are Spam = Sane*UNOFFICIAL HTML/* *Phish*
```
> Do you have spam viruses enabled?

Which setting would that be exactly?

**Comment by shawniverson** [comment] 2018-09-19 10:54
Virus Names Which Are Spam, which you have included :)

**Comment by shawniverson** [comment] 2018-09-19 11:01
Okay, so based on this config and what you have shared, the inline messages should have been prepended.

Next step will be to do some debugging.  I will walk you through that after reviewing the source code we need to trace so we can collect some additional logs.

**Comment by shawniverson** [comment] 2018-09-19 20:44
@TLINDEN which version of MailScanner are you using?

**Comment by TLINDEN** [comment] 2018-09-20 05:33
MailScanner-5.0.3_1 on FreeBSD with perl5-5.26.2.

**Comment by TLINDEN** [comment] 2018-09-20 07:12
One more thing, this is what can be seen in the mail headers of the delivered email:
```
X-MailScanner-SpamCheck: not spam,
	SpamAssassin (nicht zwischen gespeichert, Wertung=0, benoetigt 6,
	autolearn=disabled)
X-MailScanner: Found to be infected
X-MailScanner-ID: 57CD545C5307.A95B8
```

**Comment by shawniverson** [comment] 2018-10-13 19:31
@TLINDEN Would it be possible for you to send me a message source sample that is affected?  No need for the attached files, just the message structure.  This might be easier to troubleshoot with a sample.  You can email shawniverson@efa-project.org

**Comment by shawniverson** [comment] 2018-10-17 23:30
Unable to reproduce so far, still working on this to identify problem...

**Comment by shawniverson** [comment] 2018-10-27 17:59
Closing due to inability to reproduce.

**Comment by shawniverson** [comment] 2018-10-29 08:32
@TLINDEN  I sense a hint of sarcasm and distaste.  

Since I'm such a nice guy and don't read into such things, I'll reopen this issue.  

Now, based on the sample you sent me and the settings you provided, I fed it through mailscanner and it produced an inline signature.  I did it three times just to make sure, and sure enough an inline signature each time.

**Comment by TLINDEN** [comment] 2018-10-29 08:50
I already understood that couldn't reproduce the issue. So, there seems no way around that I do the debugging, since I can't send you an unaltered message because it contains sensible information of a customer. How can I do that?

I didn't want to offend, if I did, please excuse me.  But I am upset a little bit, yes - not about you but the nature of the problem. Looks like a Heisenbug and I hate those. So - again - sorry.

**Comment by shawniverson** [comment] 2018-10-29 09:03
@TLINDEN This is also a challenge because I cannot reproduce; therefore, I do not know where to advise to start debugging the code.

We can start by talking about differences in the environment.  You are on 5.0.3 running FreeBSD.  I'm on 5.2.1 running CentOS.  I can stand up a FreeBSD instance to run another test, but it will be a little while before I can do that.

**Comment by shawniverson** [comment] 2019-01-16 00:09
This looks very similar to issue https://github.com/mailwatch/MailWatch/issues/1121

**Comment by shawniverson** [comment] 2019-02-27 12:34
https://github.com/mailwatch/MailWatch/issues/1121 is not the same issue as here.  Still researching.

**Comment by shawniverson** [comment] 2019-03-03 13:58
I've noticed in the MailScanner code that there are multiple parallel things that might happen that could cause the message cleaning to be skipped for various reasons, which would mean the inline warning would not appear.  I will attempt to document them here.

**Comment by shawniverson** [comment] 2019-07-01 05:23
This line implies that "Quarantine Whole Message" is enabled, or the whole message itself was flagged as infected.

```
Sep 19 10:41:09 s4mailscan2 MailScanner[80613]: Saved entire message to /var/spool/postfix/MailScanner/quarantine/20180919/57CD545C5307.A95B8
```

Setting these to no allowed the inline message to come through consistently for me:
``` 
Quarantine Whole Message = no
ClamAV Full Message Scan = no
```

If any other A/V scanners are doing full message scanning, they can also mark the entire message as infected, instead of just the attachments.

**Comment by shawniverson** [comment] 2019-07-01 07:05
Another cause of inline messages not being signed is when the mime message cannot be parsed by SignWarningMessage in Message.pm.  If someone comes across an email that is exhibiting this behavior, I will reopen this issue and try to diagnose.

**Comment by TLINDEN** [comment] 2019-07-01 12:34
I'm not exactly sure which of the two keys must be set to "no". Currently we have both set to "yes".  Are you talking of the latter one ("ClamAV Full Message Scan")?

**Comment by shawniverson** [comment] 2019-07-01 17:01
@TLINDEN "ClamAV Full Message Scan = no" should do the trick.  Do you have other virus scanners that might be doing full scanning?

**Comment by TLINDEN** [comment] 2019-07-02 11:13
Hm, it's set to "no" for all other customers but not the one with the issue :) I'll give it a go and report if the behavior changes.

**Comment by shawniverson** [comment] 2019-07-07 13:59
@TLINDEN Closing for now, please report back if you see any other issues.  :)

**Closed by shawniverson** 2019-07-07 13:59 UTC
Labels: bug
