### ISSUE TITLE
Mailscanner send twice different ID-s message

### ISSUE THREAD

**Issue by janarzz** [MailScanner/v5#115] opened 2017-11-12 20:37 UTC
Hey,
Why mailscanner send twice different message-ID-s messages `?
My OpenDKIM test not passed: wrong body hash
When i tryng to send message without mailscanner and dkim passed..
Any ideas..

**Comment by shawniverson** [comment] 2017-11-18 11:17
@janarzz This is normal mailscanner behavior.  

Over at eFa we found that standing up a separate postfix daemon ahead of mailscanner for dkim signing is a possible solution.

Check out this post https://forum.efa-project.org/viewtopic.php?f=14&t=1006&start=25

**Comment by janarzz** [comment] 2017-11-18 15:04
Hey,
hmm i can not understund this.
I hope mailscanner takes this changes on next update.

**Comment by shawniverson** [comment] 2017-11-18 15:18
MailScanner, by design, requeues the message after scanning, therefore, it gets a new ID.  It has always worked this way.

**Comment by janarzz** [comment] 2017-11-18 15:24
Weird, old version works all perfect, but now i can install mailscanner, but OpenDKIM not work and mailwatch show duplicate messages in recent messages.
OpenDkim error: wrong body hash
MailScanner send wrong ID of message, that test not passed.

**Comment by shawniverson** [comment] 2017-11-18 15:29
Ok, that's a little more detail, you should not see duplicate messages in MailWatch.

**Comment by janarzz** [comment] 2017-11-18 15:30
When i send outgoing messages..then mailwatch show one message.
But incoming messages show mailwatch duplicate, but different ID-s

**Comment by shawniverson** [comment] 2017-11-18 15:32
Do you have a maillog you can share showing an incoming message (without sensitive info)?

**Comment by janarzz** [comment] 2017-11-18 15:38
I send test message in gmail:
Log:
Nov 18 17:34:00 meiliserver postfix/smtpd[31009]: connect from mail-qk0-f172.google.com[209.85.220.172]
Nov 18 17:34:01 meiliserver postfix/smtpd[31009]: AB3116645BB: client=mail-qk0-f172.google.com[209.85.220.172]
Nov 18 17:34:01 meiliserver postfix/cleanup[31024]: AB3116645BB: hold: header Received: from mail-qk0-f172.google.com (mail-qk0-f172.google.com [209.85.220.172])??by mail.tsutt.ee (Postfix) with ESMTPS id AB3116645BB??for <janar@tsutt.e$
Nov 18 17:34:01 meiliserver postfix/cleanup[31024]: AB3116645BB: message-id=<CAHNH3EGATCFyXeS8NE7D6NL665PP79539+rdHzHdBjdNFyFAGw@mail.gmail.com>
Nov 18 17:34:02 meiliserver postfix/smtpd[31009]: disconnect from mail-qk0-f172.google.com[209.85.220.172] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
Nov 18 17:34:02 meiliserver MailScanner[30654]: New Batch: Scanning 1 messages, 3606 bytes
Nov 18 17:34:02 meiliserver MailScanner[30654]: Virus and Content Scanning: Starting
Nov 18 17:34:13 meiliserver dovecot: imap-login: Login: user=<janar@tsutt.ee>, method=PLAIN, rip=95.153.49.146, lip=192.168.1.114, mpid=31049, TLS, session=<WX7WlUNenthfmTGS>
Nov 18 17:34:13 meiliserver dovecot: imap(janar@tsutt.ee): Logged out in=89 out=893
Nov 18 17:34:31 meiliserver MailScanner[30654]: Requeue: AB3116645BB.AE4DF to 9E02D664D3C
Nov 18 17:34:31 meiliserver MailScanner[30654]: Uninfected: Delivered 1 messages
Nov 18 17:34:31 meiliserver postfix/qmgr[21215]: 9E02D664D3C: from=<thucarus@gmail.com>, size=2590, nrcpt=1 (queue active)
Nov 18 17:34:31 meiliserver MailScanner[30654]: Deleted 1 messages from processing-database
Nov 18 17:34:31 meiliserver MailScanner[30654]: MailWatch: Logging message AB3116645BB.AE4DF to SQL
Nov 18 17:34:31 meiliserver MailScanner[30656]: MailWatch: AB3116645BB.AE4DF: Logged to MailWatch SQL
Nov 18 17:34:33 meiliserver postfix/pickup[30455]: 5EE1D664D44: uid=65534 from=<thucarus@gmail.com>
Nov 18 17:34:33 meiliserver postfix/pipe[31100]: 9E02D664D3C: to=<janar@tsutt.ee>, relay=spamassassin, delay=32, delays=29/0.01/0/2.4, dsn=2.0.0, status=sent (delivered via spamassassin service)
Nov 18 17:34:33 meiliserver postfix/qmgr[21215]: 9E02D664D3C: removed
Nov 18 17:34:33 meiliserver postfix/cleanup[31024]: 5EE1D664D44: hold: header Received: by mail.tsutt.ee (Postfix, from userid 65534)??id 5EE1D664D44; Sat, 18 Nov 2017 17:34:33 +0200 (EET) from local; from=<thucarus@gmail.com> to=<janar$
Nov 18 17:34:33 meiliserver postfix/cleanup[31024]: 5EE1D664D44: message-id=<CAHNH3EGATCFyXeS8NE7D6NL665PP79539+rdHzHdBjdNFyFAGw@mail.gmail.com>
Nov 18 17:34:35 meiliserver MailScanner[27656]: New Batch: Scanning 1 messages, 4327 bytes
Nov 18 17:34:35 meiliserver MailScanner[27656]: Virus and Content Scanning: Starting
Nov 18 17:34:51 meiliserver dovecot: imap-login: Login: user=<janar@tsutt.ee>, method=PLAIN, rip=95.153.49.146, lip=192.168.1.114, mpid=31151, TLS, session=<eUoZmENeuthfmTGS>
Nov 18 17:34:51 meiliserver dovecot: imap(janar@tsutt.ee): Logged out in=80 out=1205
Nov 18 17:34:51 meiliserver dovecot: imap-login: Login: user=<janar@tsutt.ee>, method=PLAIN, rip=95.153.49.146, lip=192.168.1.114, mpid=31154, TLS, session=<6vIcmENevNhfmTGS>
Nov 18 17:34:51 meiliserver dovecot: imap-login: Login: user=<janar@tsutt.ee>, method=PLAIN, rip=95.153.49.146, lip=192.168.1.114, mpid=31155, TLS, session=<VGAdmENevthfmTGS>
Nov 18 17:34:51 meiliserver dovecot: imap(janar@tsutt.ee): Logged out in=211 out=1124
Nov 18 17:34:51 meiliserver dovecot: imap(janar@tsutt.ee): Logged out in=1144 out=229993
Nov 18 17:35:05 meiliserver MailScanner[27656]: Requeue: 5EE1D664D44.AD7A3 to F28676645BB
Nov 18 17:35:05 meiliserver postfix/qmgr[21215]: F28676645BB: from=<thucarus@gmail.com>, size=3740, nrcpt=1 (queue active)
Nov 18 17:35:05 meiliserver MailScanner[27656]: Uninfected: Delivered 1 messages
Nov 18 17:35:05 meiliserver MailScanner[27656]: Deleted 1 messages from processing-database
Nov 18 17:35:05 meiliserver MailScanner[27656]: MailWatch: Logging message 5EE1D664D44.AD7A3 to SQL
Nov 18 17:35:05 meiliserver MailScanner[27656]: Config: calling custom end function MailWatchLogging
Nov 18 17:35:05 meiliserver MailScanner[27656]: MailScanner child dying of old age
Nov 18 17:35:05 meiliserver dovecot: lmtp(31183): Connect from local
Nov 18 17:35:05 meiliserver MailScanner[30656]: MailWatch: 5EE1D664D44.AD7A3: Logged to MailWatch SQL
Nov 18 17:35:05 meiliserver MailScanner[31184]: MailScanner Email Processor version 5.0.6 starting...
Nov 18 17:35:05 meiliserver MailScanner[31184]: Reading configuration file /etc/MailScanner/MailScanner.conf
Nov 18 17:35:05 meiliserver MailScanner[31184]: Reading configuration file /etc/MailScanner/conf.d/README
Nov 18 17:35:05 meiliserver MailScanner[31184]: Read 1500 hostnames from the phishing whitelist
Nov 18 17:35:05 meiliserver dovecot: lmtp(janar@tsutt.ee): 0pa/BilTEFrPeQAAILeQnw: sieve: msgid=<CAHNH3EGATCFyXeS8NE7D6NL665PP79539+rdHzHdBjdNFyFAGw@mail.gmail.com>: stored mail into mailbox 'INBOX'
Nov 18 17:35:05 meiliserver dovecot: lmtp(31183): Disconnect from local: Successful quit
Nov 18 17:35:05 meiliserver postfix/lmtp[31182]: F28676645BB: to=<janar@tsutt.ee>, relay=mail.tsutt.ee[private/dovecot-lmtp], delay=32, delays=32/0.02/0.01/0.15, dsn=2.0.0, status=sent (250 2.0.0 <janar@tsutt.ee> 0pa/BilTEFrPeQAAILeQnw $
Nov 18 17:35:05 meiliserver postfix/qmgr[21215]: F28676645BB: removed
Nov 18 17:35:05 meiliserver MailScanner[31184]: Read 11721 hostnames from the phishing blacklists
Nov 18 17:35:05 meiliserver MailScanner[31184]: Config: calling custom init function MailWatchLogging
Nov 18 17:35:05 meiliserver MailScanner[31184]: MailWatch: Started MailWatch SQL Logging child
Nov 18 17:35:05 meiliserver MailScanner[31184]: User's home directory /var/spool/postfix is not writable
Nov 18 17:35:05 meiliserver MailScanner[31184]: You need to set the "SpamAssassin User State Dir" to a directory that the "Run As User" can write to
Nov 18 17:35:05 meiliserver MailScanner[31184]: Using SpamAssassin results cache
Nov 18 17:35:05 meiliserver MailScanner[31184]: Connected to SpamAssassin cache database
Nov 18 17:35:05 meiliserver MailScanner[31184]: Enabling SpamAssassin auto-whitelist functionality...
Nov 18 17:35:10 meiliserver MailScanner[31184]: Connected to Processing Attempts Database
Nov 18 17:35:10 meiliserver MailScanner[31184]: Found 0 messages in the Processing Attempts Database
Nov 18 17:35:10 meiliserver MailScanner[31184]: Using locktype = flock

**Comment by shawniverson** [comment] 2017-11-18 15:46
That's strange...
It appears that dovecot is dropping the same message back into the queue?

**Comment by janarzz** [comment] 2017-11-18 15:48
When i stop Mailscanner and comment out MailScanner header conf, then all work ok.

**Comment by shawniverson** [comment] 2017-11-18 15:50
Based on this log, MailScanner is functioning properly, but I believe something is up with dovecot.  Why is dovecot pulling the message using imap, grabbing the message, and sending it back through MailScanner again?

**Comment by janarzz** [comment] 2017-11-18 15:54
I dont know..can i sholud change dovecot conf ?

**Comment by shawniverson** [comment] 2017-11-18 15:56
Probably, but I am not sure how to guide you through that....I am not a dovecot expert.  I do know it isn't right that dovecot is dropping the message back into the postfix hold queue again.

**Comment by janarzz** [comment] 2017-11-18 16:01
I dont see everything wierd postfix and dovecot conf..

**Comment by shawniverson** [comment] 2017-11-18 16:12
Yeah, but why this?  Your local instance dropping the message back into the hold queue.  You can see this is a local connection (not from gmail.com)

Nov 18 17:34:33 meiliserver postfix/cleanup[31024]: 5EE1D664D44: hold: header Received: by mail.tsutt.ee (Postfix, from userid 65534)??id 5EE1D664D44; Sat, 18 Nov 2017 17:34:33 +0200 (EET) from local; from=thucarus@gmail.com to=<janar$
Nov 18 17:34:33 meiliserver postfix/cleanup[31024]: 5EE1D664D44: message-id=CAHNH3EGATCFyXeS8NE7D6NL665PP79539+rdHzHdBjdNFyFAGw@mail.gmail.com

**Comment by janarzz** [comment] 2017-11-18 16:16
OMG finally i found problem....
/etc/postfix/master.cf conf..
I have two rows...
smtp      inet  n       -       -       -       -       smtpd
For now works perfectly :D DKIM pass ;)
Many thanks for you :)

**Comment by janarzz** [comment] 2017-11-18 16:21
Hmm...still wrong body hash when i take DKIM test :(

**Comment by shawniverson** [comment] 2017-11-18 16:24
Modifying the body at any point in mailscanner (such as a footer on the email)?

**Comment by janarzz** [comment] 2017-11-18 16:26
Hmm...i cant understund you ?

**Comment by shawniverson** [comment] 2017-11-18 16:27
"This message has been scanned by mailscanner..."

**Comment by shawniverson** [comment] 2017-11-18 16:27
Basically the message needs to pass through mailscanner with the body unaltered.

**Comment by janarzz** [comment] 2017-11-18 16:56
Why me body hash changed ?

**Comment by shawniverson** [comment] 2017-11-18 16:59
I would compare your original body to the one after it passes through mailscanner to find out.  Something must've changed.

**Comment by janarzz** [comment] 2017-11-18 17:02
What do you need for that?

**Comment by msapiro** [comment] 2017-11-18 17:24
Mailscanner changes message bodies when it disarms web bugs and phishing links.

**Comment by janarzz** [comment] 2017-11-18 17:26
Ok, but why changes mailscanner body hash, when i send outgoing mail ?

**Comment by janarzz** [comment] 2017-11-18 17:38
When i send message out, then this log:
Nov 18 19:36:44 meiliserver postfix/smtps/smtpd[4151]: connect from mail.tsutt.ee[95.153.49.146]
Nov 18 19:36:44 meiliserver postfix/smtps/smtpd[4151]: 91C67664D44: client=mail.tsutt.ee[95.153.49.146], sasl_method=PLAIN, sasl_username=janar@tsutt.ee
Nov 18 19:36:44 meiliserver postfix/cleanup[4153]: 91C67664D44: hold: header Received: from mail.tsutt.ee (mail.tsutt.ee [95.153.49.146])??by mail.tsutt.ee (Postfix) with ESMTPSA id 91C67664D44??for <thucarus@gmail.com>; Sat, 18 Nov 201$
Nov 18 19:36:44 meiliserver postfix/cleanup[4153]: 91C67664D44: message-id=<81aa56c3ca75ad00e4a40daaa2ab688e@tsutt.ee>
Nov 18 19:36:44 meiliserver postfix/smtps/smtpd[4151]: disconnect from mail.tsutt.ee[95.153.49.146] ehlo=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=6
Nov 18 19:36:44 meiliserver dovecot: imap(janar@tsutt.ee): Logged out in=958 out=483
Nov 18 19:36:44 meiliserver dovecot: imap-login: Login: user=<janar@tsutt.ee>, method=PLAIN, rip=95.153.49.146, lip=192.168.1.114, mpid=4155, TLS, session=<axQJTEVeLtxfmTGS>
Nov 18 19:36:44 meiliserver dovecot: imap(janar@tsutt.ee): Logged out in=89 out=893
Nov 18 19:36:45 meiliserver dovecot: imap-login: Login: user=<janar@tsutt.ee>, method=PLAIN, rip=95.153.49.146, lip=192.168.1.114, mpid=4157, TLS, session=<NS0KTEVeMNxfmTGS>
Nov 18 19:36:45 meiliserver dovecot: imap(janar@tsutt.ee): Logged out in=90 out=885
Nov 18 19:36:45 meiliserver MailScanner[964]: New Batch: Scanning 1 messages, 2450 bytes
Nov 18 19:36:45 meiliserver MailScanner[964]: Virus and Content Scanning: Starting
Nov 18 19:37:11 meiliserver MailScanner[964]: Expired 2 records from the SpamAssassin cache
Nov 18 19:37:13 meiliserver MailScanner[964]: Requeue: 91C67664D44.A7D7E to 2826C664D66
Nov 18 19:37:13 meiliserver postfix/qmgr[1801]: 2826C664D66: from=<janar@tsutt.ee>, size=1133, nrcpt=1 (queue active)
Nov 18 19:37:13 meiliserver MailScanner[964]: Uninfected: Delivered 1 messages
Nov 18 19:37:13 meiliserver MailScanner[964]: Deleted 1 messages from processing-database
Nov 18 19:37:13 meiliserver MailScanner[964]: MailWatch: Logging message 91C67664D44.A7D7E to SQL
Nov 18 19:37:14 meiliserver postfix/smtp[4190]: 2826C664D66: to=<thucarus@gmail.com>, relay=gmail-smtp-in.l.google.com[108.177.119.27]:25, delay=30, delays=29/0.01/0.49/0.49, dsn=2.0.0, status=sent (250 2.0.0 OK 1511026634 65si391188edm$
Nov 18 19:37:14 meiliserver postfix/qmgr[1801]: 2826C664D66: removed

**Comment by janarzz** [comment] 2017-11-18 19:20
I found this solution.
/etc/Mailscanner/Mailscnner.conf change this line to no and DKIM pass.
Sign Clean Messages

**Comment by shawniverson** [comment] 2017-11-18 19:22
:) Closing issue

**Closed by shawniverson** 2017-11-18 19:22 UTC

**Comment by janarzz** [comment] 2017-11-18 19:26
This mean mailScanner not scanning outgoing mail ?

**Comment by shawniverson** [comment] 2017-11-18 19:26
No, it means it isn't adding a footer to the email.  It is still scanning it.

**Comment by janarzz** [comment] 2017-11-18 19:28
I think this is the best solution for this issuse ?

**Comment by shawniverson** [comment] 2017-11-18 19:29
If you don't need the message in the footer, then yes.

**Comment by janarzz** [comment] 2017-11-18 19:30
But how this fix DKIM error ?

**Comment by msapiro** [comment] 2017-11-18 19:33
It fixes the DKIM problem because MailScanner no longer adds a footer to the message after it is DKIM signed.

Possibly a better solution is to not DKIM sign outbound mail until after MailScanner.

**Comment by janarzz** [comment] 2017-11-18 19:40
I just tryng this, but not working.
Sign Clean Message = no 
This works :)
